### ISSUE TITLE
Does wirefilter support BPF target?

### ISSUE THREAD

**Issue by rickyhan** [cloudflare/wirefilter#1]
In Wireshark filters are compiled to Berkeley Packet Filter which are then mounted to appropriate network interfaces by WinPcap. This avoids copying packets from kernel space to user space.

**Comment by RReverser** [comment]
It doesn't, because it's not meant for operating on packets. That said, you should be able to implement this yourself as own execution engine, while still reusing the parser.

I'm going to close this issue for now assuming it was a question and not an actual issue report.
