### ISSUE TITLE
ffi bindings

### ISSUE THREAD

**Issue by migolovanov** [cloudflare/wirefilter#2]
Hello!
I try to use this tool in lua via ffi bindings to compiled so-library, but have issues to make it work.
For example, this code works and it is possible to retreive the tool version:
```
local ffi=require("ffi") 
ffi.cdef[[ 
char* wirefilter_get_version(); 
]] 
local lib=ffi.load("./libwirefilter_ffi.so") 
local version=lib.wirefilter_get_version() 
print(ffi.string(version))
```
But when i try same approach on funtions that work with RustBox type variables it generates various errors (Segmentation fault, Illegal instruction). Seems that i miss some important part there, so can you give me a hint which variable type in C should be used to correctly work with rust variables (like RustBox)?

Thank you in advance.

**Comment by RReverser** [comment]
`RustBox<T>` translates to a regular C pointer for corresponding `T`, except for `[T]` which are a "fat" structure of data and length.

Most of these should have usage examples in their doc comments, although I now realised that we didn't publish `.h` files we use ourselves on the other side of the bindings, and probably should if people want to use this library via FFI and not just as a Rust crate.

**Comment by migolovanov** [comment]
Thank you very much for clarification, i'll try to check again, and am looking forward to `.h`-files, if you are going to publish them as well.

**Comment by RReverser** [comment]
Sure. In the meanwhile, if you could show your C headers, I could probably answer your question in more detail and hopefully address the error.

**Comment by migolovanov** [comment]
Thank you, for now it looks like this:
```
local ffi = require "ffi"

local function to_char(str)
  local c_str = ffi.new("char[?]", #str)
  ffi.copy(c_str, str)
  return c_str
end

ffi.cdef[[
struct scheme {
  char field;
  char type;
};
struct filter {
  char root_expr;
  struct scheme sch;
};
struct scheme* wirefilter_create_scheme();
void* wirefilter_add_type_field_to_scheme(struct scheme* s, char* p, int t);
struct filter* wirefilter_parse_filter(struct scheme* s, char* i);
char* wirefilter_serialize_filter_to_json(struct filter* f);
]]

local lib=ffi.load("./libwirefilter_ffi.so")
local scheme=lib.wirefilter_create_scheme()
lib.wirefilter_add_type_field_to_scheme(scheme, to_char("test"), 1)
local parse_filter=lib.wirefilter_parse_filter(scheme,to_char("test eq 1"))
local filter=lib.wirefilter_serialize_filter_to_json(parse_filter)
```

**Comment by RReverser** [comment]
Right. So the problem is that you're using `char*` (C zero-terminated strings), while we expose strings in data-length pairs.

Basically, wherever you see `StaticRustAllocatedString` / `ExternallyAllocatedStr` / `ExternallyAllocatedByteArr`, these all are represented with `ExternSliceRepr` which has an example definition in its documentation: https://github.com/cloudflare/wirefilter/blob/294292f53db18a5a3261118e93fad30bd9498b09/ffi/src/transfer_types/raw_ptr_repr/slice.rs#L5-L19

Also, types like `Scheme` and `Filter` are meant to be opaque - you don't need to describe their internal structure since all FFI APIs deal with them only via pointers.

**Comment by RReverser** [comment]
Btw, I see you're using LuaJIT FFI and copying string data before passing to `wirefilter_add_*_field_to_scheme`.

This shouldn't be necessary for `Scheme` APIs since they create own copy of the string internally, and so you can wrap Lua string into a given `ByteSlice` structure example, and pass that as-is.

**Comment by migolovanov** [comment]
Thank you very much for explanation, but i still don't understand one thing: we have two functions `wirefilter_add_type_field_to_scheme` and `wirefilter_parse_filter` that take `ExternallyAllocatedStr` parameter as input. Both times i convert lua string to ByteSlice format, but in first case the function receives:
`Ref { ptr: ExternStrRepr(ExternSliceRepr { data: 0x413f33d0, length: 4 }), ownership_marker: PhantomData }`
and in second case:
`Ref { ptr: ExternStrRepr(ExternSliceRepr { data: 0x9, length: 0 }), ownership_marker: PhantomData }`
So why in first case ByteSlice is parsed correctly, but in second case length of string is placed in data?
Code example:
```
ffi.cdef[[
typedef struct ByteSlice { 
  const uint8_t *data; 
  size_t length; 
} bs_t; 
void* wirefilter_create_scheme();
void wirefilter_add_type_field_to_scheme(void* s, struct ByteSlice p, int i);
void* wirefilter_parse_filter(void* s, struct ByteSlice i);
]]
local lib=ffi.load("./libwirefilter_ffi.so")
local scheme=lib.wirefilter_create_scheme()
local data="test"
local field_name=ffi.new("bs_t",data,#data)
lib.wirefilter_add_type_field_to_scheme(scheme,field_name,2)
local pattern="test eq 1"
local rule=ffi.new("bs_t",pattern,#pattern)
local parse_filter=lib.wirefilter_parse_filter(scheme,rule)
```

Thank you in advance.

**Comment by RReverser** [comment]
Yeah I'm not sure what's going on without further debugging of your code.

One mismatch I've noticed though (which is probably irrelevant, but still important) is that you're using `int` for the `Type` param, whereas on Rust side it's defined with `repr(u8)`, so it should be using `uint8_t` on C side instead.

**Comment by inikulin** [comment]
@migolovanov The problem is that your `cdef` states that `wirefilter_parse_filter` returns an opaque pointer, whereas in reality it returns a `ParsingResult` structure which leads to the incorrect alignment of the stack, hence you see string length in place of the pointer. Here is the fixed snippet:
```lua
local ffi = require 'ffi'

ffi.cdef[[
typedef struct wirefilter_Scheme wirefilter_Scheme;
typedef struct wirefilter_Filter wirefilter_Filter;

typedef struct ByteSlice {
  const unsigned char *data;
  size_t length;
} bs_t;

typedef struct {
    const unsigned char *data;
    size_t length;
} wirefilter_RustAllocatedStr;

typedef struct {
    uint8_t success;
    wirefilter_Filter *filter;
} wirefilter_ParsingResultOk;

typedef struct {
    uint8_t success;
    wirefilter_RustAllocatedStr msg;
} wirefilter_ParsingResultErr;

typedef union {
    uint8_t success;
    wirefilter_ParsingResultErr err;
    wirefilter_ParsingResultOk ok;
} wirefilter_ParsingResult;

wirefilter_Scheme* wirefilter_create_scheme();
void wirefilter_add_type_field_to_scheme(wirefilter_Scheme* s, struct ByteSlice p, uint8_t i);
wirefilter_ParsingResult wirefilter_parse_filter(wirefilter_Scheme* s, struct ByteSlice i);
]]

local lib=ffi.load("./target/debug/libwirefilter_ffi.dylib")
local ExternallyAllocatedByteArr = ffi.typeof("bs_t")

local function to_ffi_byte_arr(str)
    return ExternallyAllocatedByteArr(str, #str)
end

local scheme=lib.wirefilter_create_scheme()
lib.wirefilter_add_type_field_to_scheme(scheme, to_ffi_byte_arr("test"), 2)
local parse_filter=lib.wirefilter_parse_filter(scheme, to_ffi_byte_arr("test eq 1"))
```

**Comment by migolovanov** [comment]
Ah, i see. Thank you very much!

**Comment by RReverser** [comment]
I suppose this issue can be closed for now.
