### ISSUE TITLE
Usage issue: borrowed value does not live long enough

### ISSUE THREAD

**Issue by lukekhamilton** [cloudflare/wirefilter#59]
Hey guys, 

Rust Newbie here and Am in the process of trying to build a stateless function using your package. However I am getting the below error due to the lifetime usage in the function signature and for the life of me I cant seam to work this one out. 

Please see sample code here where I am getting this error: 

https://github.com/lukekhamilton/rust-adventures/blob/master/debugging/wirefilter_issue/src/main.rs
 
Any help greatly appreciated. 
L

```
error[E0597]: `data.rule` does not live long enough
  --> src/main.rs:24:28
   |
24 |     let ast = scheme.parse(&data.rule)?; //  borrowed value does not live long enough??? HELP
   |               -------------^^^^^^^^^^-
   |               |            |
   |               |            borrowed value does not live long enough
   |               argument requires that `data.rule` is borrowed for `'static`
...
36 | }
   | - `data.rule` dropped here while still borrowed

```

**Comment by inikulin** [comment]
If you take a look at [Scheme::parse](https://docs.rs/wirefilter-engine/0.6.1/wirefilter/struct.Scheme.html#method.parse) function signature you'll notice that in case of error result `ParseError` should have the same lifetime `'i` as `input`. 

You pass `data` by value in `process_rule_data` which means that it will be dropped (and its field `rule`) once this function return. But, you force `Scheme::parse`'s to return error to outer scope by using `?` operator. And that causes the issue: you try to return error from `process_rule_data` function that borrows the value (`rule.data`) which will be dropped when function return.

To workaround that: either pass data by reference (i.e. `data: &Data`) in  `process_rule_data` or unwrap parse error (`scheme.parse(&data.rule).unwrap()`), whatever is more suitable for you use case.

**Comment by RReverser** [comment]
To add to what Ivan said - instead of unwrapping the error (which is probably something you don't want to do when using error handling library like `failure`), you can convert it to `String` and return using `.map_err(|err| err.to_string())?`.

**Comment by lukekhamilton** [comment]
@inikulin you are a Legend. Thanks. The second options works perfectly. 

Just out of interest why the need for the `'i as input' for `ParseError` anyway?

**Comment by lukekhamilton** [comment]
Hey @RReverser, not sure I understand what you mean when you say `(which is probably something you don't want to do when using error handling library like failure)` could you expand on why that is for me? Thanks //Newbie still. :D

**Comment by RReverser** [comment]
> could you expand on why that is for me

Because that way you have a chance to handle errors in a uniform layer somewhere higher up the function chain, while with `.unwrap()` you'll crash a program immediately. In some cases this might be fine, but in other situations it might end up being a problem, and so it's not a common / idiomatic practice.

**Comment by lukekhamilton** [comment]
Oh I I get you now. Thank heaps for explaining that one @RReverser :)
