### ISSUE TITLE
wirefilter does not support CIDR format?

### ISSUE THREAD

**Issue by tommy-dong** [cloudflare/wirefilter#84]
wirefilter does not support CIDR format:
ip.addr == 192.168.0.1/24 --- not supported
ip.addr >= 192.168.0.1 and ip.addr <= 192.168.0.64 --- supported

**Comment by marmeladema** [comment]
It does but you need to use the `in {}` operator.

**Comment by marmeladema** [comment]
Closing for now, feel free to re-open if needed 👍
